# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6b5f98bf5fecaf5a0ca3b0472fc15503f7cc2e5db9135cccc9e540b1969b2a9828013207ceb077ce443324ffa0de83c2fa45233c0ba5f13cd2b16376a8e2bf4

test:
  secret_key_base: 0c3427a8ae5bdfa2f48f8f0630efe5b26fc079c904cbcf488eb66405573a8738058b1232b43ada2304b0c7f7207e8ff099a41ef6b68c4f80e0fd7ead7f221e7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
